apiVersion: apps/v1
kind: Deployment
metadata:
  name: calculator-app-deployment
  labels:
    app: calculator-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: calculator-app
  template:
    metadata:
      labels:
        app: calculator-app
    spec:
      containers:
        - name: nodeserver
          image: dghallay/calculator-app:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
---

