apiVersion: v1
kind: Service
metadata:
  name: calculator-app-service
spec:
  selector:
    app: calculator-app 
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 3040
    nodePort: 31110